[package]
name = "starlink-grpc-client"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tonic-build = "0.9"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
tonic = { version = "0.9", features = ["transport"] }
prost = "0.11"
prost-types = "0.11"
thiserror = "1.0"
